package Interface;

public class Res extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][] { { "Copyright_c_2004", "Copyright (c) 2004" },
			{ "about_png", "about.png" }, { "Apropos", "A propos" },
			{ "drmdh_Copyright_c", "drmdh Copyright (c) 2004" }, { "Ok", "Ok" },
			{ "Bienvenue_sur_NetGame", "\tBienvenue sur NetGame le combat � mort ." },
			{ "apr_s_identification", "  apr�s identification cliquez sur accepter vous vous connectez" },
			{ "au_serveur_avec_votre", "  au serveur avec votre login. Le jeu commencera � l\'arriv�e du" },
			{ "quatri_me_joueur_vous", "  quatri�me joueur, vous avez la possibilit� de diriger vos tirs" },
			{ "contre_qui_vous", "  contre qui vous voulez, vous serez autoris� � de nouvelles" },
			{ "tentatives_de_tirs", "  tentatives de tirs une fois que tous les adversaires ont fini" },
			{ "leur_tour_", "  leur tour. " },
			{ "_les_carr_s_rouges", " * les carr�s rouges signifient que le coup est tomb� dans l\'eau " },
			{ "_les_carr_s_magentas", " * les carr�s magentas : les bateaux touch�s." },
			{ "images_netgamelogoi", "rc/media/images/netgamelogoi.gif" },
			{ "images_Tortu_jpg", "rc/media/images/Tortu.jpg" },
			{ "vous_n_avez_pas_le", " vous n\'avez pas le droit de tirer des misilles contre vous meme" },
			{ "le_jeu_n_a_pas_encor", " le jeu n\'a pas encor commenc� ou attendez le prochain tour  " },
			{ "la_case_est_d_ja_s_l", "la case est d�ja s�l�ctionn�  " },
			{ "images_earth_jpg", "rc/media/images/earth.jpg" }, { "openFile_png", "openFile.png" },
			{ "closeFile_png", "closeFile.png" }, { "help_png", "help.png" }, { "cap_jpg", "cap.jpg" },
			{ "nocap_png", "nocap.png" }, { "nocapup_png", "nocapup.png" }, { "gomusic_png", "gomusic.png" },
			{ "stopmus_png", "stopmus.png" }, { "Fichier", "Fichier" }, { "Quitter", "Quitter" }, { "Aide", "Aide" },
			{ "Tableau_chat", "Tableau chat" }, { "dr_Madani_Hamid_drmdh", "dr Madani Hamid   drmdh@free.fr" },
			{ "EditorPane", "EditorPane.selectionBackground" }, { "rotation", "rotation" }, { "HI_B_L", "HI B L" },
			{ "R1", "R1" }, { "R2", "R2" }, { "R3", "R3" }, { "Help", "Help" }, { "Server_On", "Server On" },
			{ "Server_OFF", "Server OFF" }, { "Dialog", "Dialog" }, { "connexion", "connexion" },
			{ "Client_On", "Client On" }, { "Client_OFF", "Client OFF" }, { "Kill_All", "Kill All" },
			{ "Sendbt", "Sendbt" }, { "Send", "Send" }, { "Connexion", "Connexion" }, { "PrInfos", "PrInfos" },
			{ "AllPerson", "AllPerson" }, { "InitGame", "InitGame" }, { "Msg", "Msg" }, { "Arial", "Arial" },
			{ "reception_et_envoi_de", "reception et envoi de m�ssage" }, { "Quiter", "Quiter" },
			{ "Quiter_", "       Quiter ... " }, { "ObservateurBt", "ObservateurBt" }, { "Observateur", "Observateur" },
			{ "Apropos_", "Apropos_" }, { "Apropos1", "Apropos" }, { "jButton2", "jButton2" }, { "Sounds", "Sounds" },
			{ "clic_to_stop_or_run", "clic to stop or run music" }, { "muted", "muted" },
			{ "clic_to_strat", "clic to strat captures" }, { "captureC", "captureC" },
			{ "observateur_log", "observateur log" }, { "jButton1", "jButton1" }, { "Replay", "Replay" },
			{ "start", "start" }, { "connectme", "connectme" }, { "identification", "identification" },
			{ "set_infos", "set infos" }, { "connection", "connection" }, { "Game_Number_one", "Game Number one" },
			{ "Game", "Game" }, { "chat", "chat" }, { "Communication", "Communication" },
			{ "Apropos_des_auteurs", "A propos des auteurs " }, { "NerGame_version_1_0", " NerGame version 1.0  logo" },
			{ "bye_bye", "bye bye" }, { "You_are_", "You are: \n" }, { "Connection_to_", "Connection to  : \n" },
			{ "port_", "port : \n" }, { "not_yet_implemented", "   not yet implemented " }, { "Chat", "   Chat " },
			{ "ce_nom_de_serveur_ou", "ce nom de serveur ou port est a verifier " },
			{ "nombre_de_vecteur", "nombre de vecteur bateaux " },
			{ "nombre_de_point_par", "nombre de point par vecteur(baleaux) : " },
			{ "CadrePr", "CadrePr.showAllNavires : whereIam() " },
			{ "CadrePr1", "CadrePr.showAllNavires : whoIam().getNum()" },
			{ "CadrePR", "CadrePR.Replay_actionPerformed who = " },
			{ "CadrePR1", "CadrePR.Replay_actionPerformed getQui() = " },
			{ "images_requin_gif", "rc/media/images/requin.gif" },
			{ "Bienvenue_sur_NetGame1", "\tBienvenue sur NetGame le (combat � mort)\n" },
			{ "apr_s_identification1", "  apr�s identification cliquez sur accepter vous vous connectez\n" },
			{ "au_serveur_avec_votre1", "  au serveur avec votre login. Le jeu commencera � l\'arriv�e du\n" },
			{ "quatri_me_joueur_vous1", "  quatri�me joueur, vous avez la possibilit� de diriger vos tirs\n" },
			{ "contre_qui_vous1", "  contre qui vous voulez, vous serez autoris� � de nouvelles\n" },
			{ "tentatives_de_tirs1", "  tentatives de tirs une fois que tous les adversaires ont fini\n" },
			{ "leur_tour_1", "  leur tour. \n" },
			{ "_les_carr_s_rouges1",
					" * les carr�s rouges signifient que le coup est tomb� dans l\'eau " + "\" +\n    \"\n" },
			{ "Pr_nom", "Pr�nom" }, { "port_1", "port *                  " },
			{ "connect_and_play", "connect and play" }, { "Nom", "Nom" }, { "Nom1", "Nom                     " },
			{ "Mail", "Mail                      " }, { "login", "login" }, { "Prenom", "Prenom                " },
			{ "younes", "younes" }, { "start_serveur", "start serveur" },
			{ "start_as_serveur_", "  start as serveur      ..." }, { "Mail1", "Mail" }, { "accepter", "   accepter " },
			{ "server_name_", "server  name *" }, { "MenuBar_foreground", "MenuBar.foreground" },
			{ "login_", "login *                 " }, { "Abadi_MT_Condensed", "Abadi MT Condensed Extra Bold" },
			{ "corrigez_le_numero_de", "corrigez le numero de port" }, { "_log", ".log" },
			{ "client_connect_", " client connect�" }, { "probl_me_connexion_r", "  probl�me connexion r�seau" },
			{ "al_coute", "  a l\'�coute" }, { "probl_me_de_mise_en", "  probl�me de mise en route du serveur " },
			{ "les_navires_du_joueur", "les navires du joueur " }, { "partie", " partie " },
			{ "debut_de_la_", "\n\tdebut de la : " },
			{ "les_joueurs_au_tour", " les joueurs au tour de la table sont :\n" },
			{ "joueur_s_en_ligne", " joueur(s) en ligne" }, { "il_y_a", "\t  il y a  " }, { "il_y_a1", "il y a  " },
			{ "joueur_s_en_ligne1", "joueur(s) en ligne" }, { "en_ligne", " en ligne" }, { "X", "        X    " },
			{ "Game_Over", "Game Over" }, { "coups_", " coups()" }, { "superviseur_forward", " superviseur.forward  " },
			{ "Seperviseur_", "Seperviseur." }, { "Match_null_aucun", "Match null aucun survivant" },
			{ "Nous_attandons_La",
					"\t\n Nous attandons La confirmation de l\'enssembles des joueurs pour "
							+ "\" +\n    \"la reprise   : " },
			{ "The_winer_is", "The winer is " }, { "The_winer_is_", "\t\n The winer is   : " },
			{ "le_cycle_N_", "\t le cycle N�: " }, { "le_coup", "le coup " },
			{ "envoy_par_le_joueur_", " envoy� par le joueur : " }, { "contre_le_joueur_", " contre le joueur : " },
			{ "sur_la_position_", " sur la position  :" }, { "GO", "GO    " },
			{ "pour_le_tour_N_", " pour le tour N�: " }, { "Attendez", "Attendez       " },
			{ "le_tour_N_", " le tour N�: " }, { "Wait_for_lap_", " Wait for lap # " },
			{ "Un_nouveau_coup_a_t", "Un nouveau coup a �t� envoy�" },
			{ "Attention_l_erreur", "Attention l\'erreur suivante s\'est produite:  \n" },
			{ "Fin_de_partie_", "\t\t    Fin de partie :" },
			{ "Superviser_notifyR", "Superviser.notifyR�initGameFromClient : JoueurVivants" } };

	public Object[][] getContents() {
		return contents;
	}
}
